let joke = [
` “It is never late to be what you might have been. ”- George Eliot.`,
`“Imagination is more important than knowledge. ”- Albert Einstein.`,
`“Success usually comes to those who are too busy to be looking for it. ”- Henry David Thoreau.`,
`“It’s not whether you get knocked down, it’s whether you get up. ”-Vince Lombardi.`,
`"The greatest pleasure in life is doing what people say you cannot do." - Walter Bagehot.`,
`"You must be the change you wish to see in the world. ”- Mahatma Gandhi`,
`“What lies behind us and what lies before us are tiny matters compared to what lies within us.”-HENRY S. HASKINS`,
`"Success is walking from failure to failure with no loss of enthusiasm. ”- Winston Churchill`,
`“If You Are Working On Something That You Really Care About, You Don’t Have To Be Pushed. The Vision Pulls You.” – Steve Jobs`,
`“Life begins at the end of your comfort zone." — Neale Donald Walsch.`,
`"Courage is grace under pressure." - Ernest Hemingway`,
`“Security is mostly a superstition. Life is either a daring adventure or nothing.” – Helen Keller`,
`“The future cannot be predicted, but futures can be invented. ”-- DENNIS GABOR`,
`“All our dreams can come true if we have the courage to pursue them.” - Walt Disney.`,
`“No one can make you feel inferior without your consent ”- Eleanor Roosevelt`,
`"Try not to become a person of success, but rather try to become a person of value." - Albert Einstein`,
`“The Pessimist Sees Difficulty In Every Opportunity. The Optimist Sees Opportunity In Every Difficulty.” – Winston Churchill`,
`“Someone is sitting in the shade today because someone planted a tree a long time ago." - Warren Buffett`,
`“Motivation is the art of getting people to do what you want them to do because they want to do it.” – Dwight D. Eisenhower`,
`“It is never too late to be what you might have been.” - GEORGE ELIOT`,
`“Live life to the fullest.”- R L Stevenson`,
`“Above all to thine own self be true. ”- William Shakespeare`,
`“Whenever you see a successful person, you only see the public glories, never the private sacrifices to reach them." - Vaibhav Shah`,
`“People Who Are Crazy Enough To Think They Can Change The World, Are The Ones Who Do.” – Rob Siltanen`,
`"Great minds discuss ideas; average minds discuss events; small minds discuss people. ”- Eleanor Roosevelt`,
`"Once you choose hope, anything's possible." - Christopher Reeve`,
`“Change your life today. Don’t gamble on the future, act now, without delay.” – Simone de Beauvoir`,
`“You make a living by what you get; you make a life by what you give.” -WINSTON CHURCHILL`,
`“Don’t Let Yesterday Take Up Too Much of Today. ”- Will Rogers`,
`“If you can dream it, you can do it.”- Walt Disney”`,
`"It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change." - Charles Darwin`,
`“Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.”— Earl Nightingale`,
`“Two things define you: Your patience when you have nothing and your attitude when you have everything. ”- Imam Ali`,
`The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart." -Helen Keller`,
`“Motivation is what gets you started. Habit is what keeps you going.” – Jim Ryun`,
`“A river cuts through the rock, not because of its power, but because of its persistence”- Jinti Watkins`,
`“A dream doesn't become reality through magic; it takes sweat, determination, and hard work. ”- Colin Powell`,
`“People will forget what you said. People will forget what you did. But people will never forget how you made them feel.” - MAYA ANGELOU`,
`“Obstacles are those frightful things you see when you take your of your goals.” - Henry Ford`,
`“You don’t have to be great to start, but you have to start to be great.” — Zig Ziglar`,
`"The more you praise and celebrate your life, the more there is in life to celebrate." - Oprah Winfrey`,
`“It always seems impossible until it is done. ”- Nelson Mandela`,
`“Motivation comes from working on things we care about.” – Sheryl Sandberg`,
`“Some cause happiness wherever they go; others, whenever they go.” OSCAR WILDE`,
`“A journey of a thousand miles begins with a single step.” - Confucius`,
`“The distance between insanity and genius is measured only by success." - Bruce Feirstein`,
`“Imagine Your Life Is Perfect In Every Respect; What Would It Look Like?” – Brian Tracy`,
`“If it is important to you, you will find a way. If not, you’ll find an excuse.” — Ryan Blair`,
`“Pain is weakness leaving the body.”— the United States Marine Corps`,
`Live as if you were to die tomorrow. Learn as if you were to live forever." -Mahatma Gandhi`,
`“Progress is the ultimate motivation.” – Tony Robbins`,
`"There are two primary choices in life" to accept conditions as they exist, or accept the responsibility for changing them." - DENIS WAITLEY`,
`“Do not follow where the path may lead. Go instead where there is no path and leave a trail.”- Ralph Waldo Emerson`,
`"Don't be afraid to give up the good to go for the great." John D. Rockefeller`,
`“We Generate Fears While We Sit. We Overcome Them By Action.” – Dr. Henry Link`,
`“Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.”— Earl Nightingale`,
`“Get comfortable with being uncomfortable.”— Jillian Michaels`,
`“Once you choose hope, anything's possible." - Christopher Reeve`,
`“A man who has committed a mistake and doesn’t correct it is committing another mistake.” – Confucius`,
`“Perfection is not attainable, but if we chase perfection we can catch excellence.” - VINCE LOMBARDI`,
`“The best way to cheer yourself up is to try to cheer somebody else up.”- Mark Twain`,
`“Success is walking from failure to failure with no loss of enthusiasm." - Winston Churchill`,
`“Reading Is To The Mind, As Exercise Is To The Body.” – Brian Tracy`,
`"When you cease to dream you cease to live." - Malcolm Forbes`,
`“Be sure you put your feet in the right place, then stand firm.” – Abraham Lincoln`,
`“Challenges are what make life interesting and overcoming them is what makes life meaningful.”- JOSHUA J. MARINE`,
`“What we see depends mainly on what we look for”- Sir John Lubbock`,
`"The distance between insanity and genius is measured only by success." Bruce Feirstein`,
`"The difference between winning and losing is most often not quitting." -Walt Disney`,
`“Courage is resistance to fear, mastery of fear–not absence of fear.” – Mark Twain`,
`“Many of life’s failures are experienced by people who did not realize how close they were to success when they gave up.”-THOMAS EDISON`,
`“The definition of insanity is doing the same thing over and over and expecting different results”. Albert Einstein`,
`"Don't be afraid to give up the good to go for the great." - John D. Rockefeller`,
`“A Room Without Books Is Like A Body Without A Soul.” – Marcus Tullius Cicero`,
`"Failure is another steppingstone to greatness." - Oprah Winfrey`,
`“Defeat is a state of mind; no one is ever defeated until defeat is accepted as a reality.” – Bruce Lee`,
`“People are illogical, unreasonable, and self-centered. Love them anyway.” - KENT M. KEITH`,
`“Life shrinks or expands in proportion to one’s courage.” - Anais Nin`,
`"Success is the sum of small efforts, repeated day in and day out." - Robert Collier`,
`“I Think Goals Should Never Be Easy, They Should Force You To Work, Even If They Are Uncomfortable At The Time.” – Michael Phelps`,
`"You miss 100% of the shots you don't take." -Wayne Gretzky`,
`“I believe that the only courage anybody ever needs is the courage to follow your own dreams.” – Oprah Winfrey`,
`“I will not follow where the path may lead, but I will go where there is no path, and I will leave a trail.” - MURIEL STRODE`,
`“Dreams are renewable no matter what our age.” - Dale Turner`,
`“Courage is resistance to fear, mastery of fear -- not absence of fear." Mark Twain`,
`“One Of The Lessons That I Grew Up With Was To Always Stay True To Yourself And Never Let What Somebody Else Says Distract You From Your Goals.” – Michelle Obama`,
`"You must expect great things of yourself before you can do them." -Michael Jordan`,
`“If you want something you’ve never had, you must be willing to do something you’ve never done.” – Thomas Jefferson`,
`“By the time a man realizes that his father was right, he has a son who thinks he's wrong.” - CHARLES WADSWORTH`,
`“You see things and you say, Why? But I dream things that never were and say, Why not?” – George Bernard Shaw`,
`"The No. 1 reason people fail in life is because they listen to their friends, family, and neighbors." Napoleon Hill`,
`“Today’s Accomplishments Were Yesterday’s Impossibilities.” – Robert H. Schuller`,
`"If your actions inspire others to dream more, learn more, do more and become more, you are a leader." -John Quincy Adams`,
`“When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.” – Henry Ford`,
`“Remember that happiness is a way of travel, not a destination.”- ROY L. GOODMAN`,
`“Happiness lies in the joy of achievement and the thrill of creative effort.” Franklin D. Roosevelt`,
`"You may have to fight a battle more than once to win it." Margaret Thatcher`,
`“You Don’t Have To Be Great To Start, But You Have To Start To Be Great.” – Zig Ziglar`,
`"If at first you don't succeed, try, try, try again." -William Edward Hickson`,
`“Things may come to those who wait, but only the things left by those who hustle.” – Abraham Lincoln`,
`“If you steal from one author, it’s plagiarism; if you steal from many, it’s research.” - WILSON MIZNER`,
`“Happiness lies in the joy of achievement and the thrill of creative effort.” Franklin D. Roosevelt`,
`“Successful and unsuccessful people do not vary greatly in their abilities. They vary in their desires to reach their potential." - John Maxwell`,
`“Leaders Never Use The Word Failure. They Look Upon Setbacks As Learning Experiences.” Brian Tracy`,
`"Don't count the days, make the days count." -Muhammad Ali`,
`“When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.” – Henry Ford”`,
`“You cannot teach a man anything; you can only help him find it within yourself.” – Galileo Galilei`,
`“Successful and unsuccessful people do not vary greatly in their abilities. They vary in their desires to reach their potential." - John Maxwell`,
`“A good plan violently executed now is better than a perfect plan executed next week.” – George S. Patton`,
`“Management is doing things right; leadership is doing the right things.”- Peter F Drucker`,
`“The unexamined life is not worth living.”- Socrates`,
`"Focus on the journey, not the destination. Joy is found not in finishing an activity but in doing it." Greg Anderson`,
`"We must accept finite disappointment, but never lose infinite hope." -Martin Luther King, Jr.`,
`“You can never cross the ocean until you have the courage to lose sight of the shore.” – Christopher Columbus`,
`“The only person you are destined to become is the person you decide to be.” - RALPH WALDO EMERSON`,
`“Many receive advice, only the wise profit from it.” – Publilius Syrus`,
`“Happiness is where we find it, but very rarely where we seek it." - J. Petit Senn`,
`"Every moment is a fresh beginning." - T.S. Eliot`,
`“I attribute my success to this: I never gave or took an excuse.” – Florence Nightingale`,
]
// console.log(a)

// console.log(joke[a])
// let p=document.body.getElementsByTagName("p")
// console.log(p)

  let a= Math.floor(Math.random()*joke.length-1)
  para.innerHTML= joke[a]
     